company/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('employees.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

employees/urls.py
from django.urls import path
from . import views

app_name = 'employees'

urlpatterns = [
    path('', views.HomePageView.as_view(), name='home-page'),
    path('blog/', views.BlogPageView.as_view(), name='blog-page'),
    path('about/', views.AboutPageView.as_view(), name='about-page'),
    path('services/', views.ServicePageView.as_view(), name='service-page'),
    path('feature/', views.FeaturePageView.as_view(), name='feature-page'),
    path('pricing/', views.PricePageView.as_view(), name='price-page'),
    path('quote/', views.QuotePageView.as_view(), name='quote-page'),
    path('team/', views.TeamPageView.as_view(), name='team-page'),
    path('testimonial/', views.TestimonialPageView.as_view(), name='testimonial-page'),
    path('contact/', views.ContactPageView.as_view(), name='contact-page'),
    path('post-detail/<int:pk>/', views.PostDetailView.as_view(), name='post-detail'),
    path('auth/login/', views.LoginView.as_view(), name='login-page'),
    path('auth/register/', views.RegisterView.as_view(), name='register-page'),
    path('auth/logout/', views.LogoutView.as_view(), name='logout-page'),
    path('auth/lockscreen/', views.LockScreenView.as_view(), name='lockscreen-page'),
    path('info/', views.ContactFormView.as_view(), name='contactform-page'),
    path('createblog/', views.CreatePostView.as_view(), name='post-page'),
    path('delete-post/<int:pk>/', views.DeletePostView.as_view(), name='post-delete'),
    path('update-post/<int:pk>/', views.UpdatePostView.as_view(), name='post-update'),

]

employees/models.py
from django.db import models
from django.core.validators import MinValueValidator
from django.contrib.auth import get_user_model
from django.utils import timezone

current_time = timezone.now()


User = get_user_model()



DESIGNATION_CHOICES = [
    ('chaiperson','chairperson'),
    ('secretary','secretary'),
    ('finance manager','finance manager'),
    ('Product manager','Product manager'),
]

# Create your models here.
    
class Department(models.Model):
    name = models.CharField(max_length=40)
    manager = models.OneToOneField(User, on_delete=models.SET_NULL, null=True, blank=True)
    
    def __str__(self):
        return self.name
    
    
class Employee(models.Model):
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)
    age = models.IntegerField(validators=[MinValueValidator(0)])
    department =  models.ForeignKey(Department, on_delete=models.SET_NULL, null=True, blank=True)
    
    def __str__(self):
        return self.first_name
  
class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    posttype = models.CharField(max_length=100)
    description = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    image = models.ImageField(upload_to='media', blank=False, null=False)
    content = models.TextField()
    
    def __str__(self):
        return self.title
    
class Staff(models.Model):
    details = models.ForeignKey(User, on_delete=models.CASCADE)
    designation = models.CharField(max_length=100, choices=DESIGNATION_CHOICES)
    profilepic = models.ImageField(upload_to='media', blank=False)
    
    def __str__(self):
        return self.details.username
    
class Message(models.Model):
    name = models.CharField(max_length=20)
    email = models.EmailField()
    subject = models.CharField(max_length=100)
    message = models.TextField()
    
    def __str__(self):
        return self.subject

employees/forms.py
from django.forms import ModelForm
from .models import Post

class PostCreationForm(ModelForm):
    
    class Meta:
        model = Post
        fields = ("title", "posttype", "description",
                  "image", "content")

employees/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from django.views import View
from .models import Post,Staff, Message
from django.contrib.auth import login, logout, authenticate
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.contrib.auth.models import User

# Create your views here.
class HomePageView(View):
    def get(self, request):
        return render(request, 'employees/base.htm')

@method_decorator(login_required(login_url='employees:login-page'), name='get') 
class BlogPageView(View):
    def get(self, request):
        posts = Post.objects.all()
        context = {
            'posts':posts
        }
        return render(request, 'employees/blog.htm', context)
    
class ServicePageView(View):
    def get(self, request):
        return render(request, 'employees/services.htm')

@method_decorator(login_required(login_url='employees:login-page'), name='get')    
class PricePageView(View):
    def get(self, request):
        return render(request, 'employees/price.htm')

@method_decorator(login_required(login_url='employees:login-page'), name='get')     
class QuotePageView(View):
    def get(self, request):
        return render(request, 'employees/quote.htm')

@method_decorator(login_required(login_url='employees:login-page'), name='get')     
class TeamPageView(View):
    def get(self, request):
        staff = Staff.objects.all()
        context = {
            'staff':staff
        }
        return render(request, 'employees/team.htm', context)

@method_decorator(login_required(login_url='employees:login-page'), name='get')     
class TestimonialPageView(View):
    def get(self, request):
        return render(request, 'employees/testimonial.htm')

@method_decorator(login_required(login_url='employees:login-page'), name='get')     
class ContactPageView(View):
    def get(self, request):
        return render(request, 'employees/contact.htm')
    def post(self, request):
        name = request.POST['username']
        email = request.POST['email']
        subject = request.POST['subject']
        message = request.POST['message']

        newcontact = Message.objects.create(name=name, email=email, subject=subject, message=message)
        newcontact.save()
        messages.success(request, "We have received your message. Thankyou for contacting Uncle P Edits. We'll get back to you soon")
        return redirect('employees:home-page')

@method_decorator(login_required(login_url='employees:login-page'), name='get')     
class FeaturePageView(View):
    def get(self, request):
        return render(request, 'employees/feature.htm')

class AboutPageView(View):
    def get(self, request):
        return render(request, 'employees/about.htm')

@method_decorator(login_required(login_url='employees:login-page'), name='get')     
class PostDetailView(View):
    def get(self, request, pk):
        post = Post.objects.get(id=pk)
        context = {
            'post':post,
        }
        return render(request, 'employees/post-details.htm', context)
    
class LoginView(View):
    def get(self, request):
        return render(request, 'employees/authentication/login.htm')
    
    def post(self, request):
           
        username = request.POST['username']
        password = request.POST['password']
        
        user = authenticate(username=username, password=password)
        if user is not None: 
            login(request, user)
            messages.success(request, "Successfully logged in")
            return redirect('employees:home-page')
        else:
            messages.info(request, "Credentials do not match")
            return redirect('employees:login-page')
        
        return render(request, 'employees/authentication/login.htm')

class RegisterView(View):
    def get(self, request):
        return render(request, 'employees/authentication/register.htm')
    
    def post(self, request):
        users = User.objects.all()
        username = request.POST['username']
        email = request.POST['email']
        password1 = request.POST['password1']
        password2 = request.POST['password2']
        
        if password1 != password2:
            messages.warning(request, "Passwords do not match")
            return redirect('employees:register-page')
        if len(password1) and len(password2) < 8:
            messages.warning(request, "Password must be 8 or more characters")
            return redirect('employees:register-page')

        exists = User.objects.filter(email=email)
        if exists:
            messages.warning(request, "Email already taken")
            return redirect('employees:register-page')
        else:
            user = User.objects.create(username=username, email=email, password=password1)
            user.save()
            messages.success(request, "User created successfully")
            return redirect('employees:login-page')
        return render(request, 'employees/authentication/login.htm')

    
class LogoutView(View):
    def get(self, request):
        logout(request)
        messages.success(request, "successfully logged out")
        return redirect('employees:login-page')
    
class LockScreenView(View):
    def get(self, request):
        return render(request, 'employees/authentication/lockscreen.htm')
    def post(self, request):
        password = request.POST['password1']
        username = request.user.username
        exists = User.objects.filter(username=username)
        if password == exists.password:
            return redirect('employees:home-page')
        else:
            messages.warning(request, "Wrong password")
            return redirect('employees:lockscreen-page')
        

class ContactFormView(View):
    def get(self, request):
        id = request.user.id
        user_instance = get_object_or_404(User, id=id)
        return render(request, 'employees/contact.htm')
    
    def post(self, request):
        name = request.POST['username']
        email = request.POST['email']
        subject = request.POST['subject']
        message = request.POST['message']

        newcontact = Message.objects.create(name=name, email=email, subject=subject, message=message)
        newcontact.save()
        messages.success(request, "We have received your message. Thankyou for contacting Uncle P Edits. We'll get back to you soon")
        return redirect('employees:home-page')
 
@method_decorator(login_required(login_url='employees:login-page'), name='dispatch')
class CreatePostView(View):
    def get(self, request):
        return render(request, 'employees/create-post.htm')
    
    def post(self, request):
        logged = request.user.username
        author = User.objects.get(username=logged)
        title = request.POST['title']
        posttype = request.POST['posttype']
        description = request.POST['description']
        image = request.FILES['image']
        content = request.POST['content']
        
        blogpost = Post.objects.create(author=author, title=title, posttype=posttype, description=description, content=content)
        blogpost.image = image  
        blogpost.save()
        
        messages.success(request, "You have successfully created a new post")
        return redirect('employees:blog-page')

@method_decorator(login_required(login_url='employees:login-page'), name='post')
class UpdatePostView(View):
    def get(self, request, pk):

        post = get_object_or_404(Post, id=pk)


        if request.user != post.author:
            messages.error(request, "You don't have permission to edit this post.")
            return redirect('employees:blog-page')

        context = {
            'post': post,
        }
        return render(request, 'employees/update-post.htm', context)
    
    def post(self, request, pk):

        post = get_object_or_404(Post, id=pk)


        if request.user != post.author:
            messages.error(request, "You don't have permission to edit this post.")
            return redirect('employees:blog-page')


        post.title = request.POST['title']
        post.posttype = request.POST['posttype']
        post.description = request.POST['description']
        post.content = request.POST['content']

        if 'image' in request.FILES:
            post.image = request.FILES['image']

        post.save()

        messages.success(request, "Post updated successfully")
        return redirect('employees:blog-page')
    
@method_decorator(login_required(login_url='employees:login-page'), name='dispatch')
class DeletePostView(View):
    def get(self, request, pk):
        return render(request, 'employees/delete-post.htm')
    def post(self, request, pk):
        post = Post.objects.get(id=pk)
        if request.user != post.author:
            messages.warning(request, "You don't have permissions to edit this post.")
            return redirect('employees:blog-page')
        post.delete()
        messages.success(request, "Post deleted successfully")
        return redirect('employees:blog-page')
    

employees/templates/employees/about.htm
{% extends "employees/base.htm" %}
{% load static %}

{% block content %}
  

<!-- About Start -->
    <div class="container-fluid py-5 wow fadeInUp" data-wow-delay="0.1s">
        <div class="container py-5">
            <div class="row g-5">
                <div class="col-lg-7">
                    <div class="section-title position-relative pb-3 mb-5">
                        <h5 class="fw-bold text-primary text-uppercase">About Us</h5>
                        <h1 class="mb-0">The Best IT Solution With 10 Years of Experience</h1>
                    </div>
                    <p class="mb-4">Tempor erat elitr rebum at clita. Diam dolor diam ipsum et tempor sit. Aliqu diam amet diam et eos labore. Clita erat ipsum et lorem et sit, sed stet no labore lorem sit. Sanctus clita duo justo et tempor eirmod magna dolore erat amet</p>
                    <div class="row g-0 mb-3">
                        <div class="col-sm-6 wow zoomIn" data-wow-delay="0.2s">
                            <h5 class="mb-3"><i class="fa fa-check text-primary me-3"></i>Award Winning</h5>
                            <h5 class="mb-3"><i class="fa fa-check text-primary me-3"></i>Professional Staff</h5>
                        </div>
                        <div class="col-sm-6 wow zoomIn" data-wow-delay="0.4s">
                            <h5 class="mb-3"><i class="fa fa-check text-primary me-3"></i>24/7 Support</h5>
                            <h5 class="mb-3"><i class="fa fa-check text-primary me-3"></i>Fair Prices</h5>
                        </div>
                    </div>
                    <div class="d-flex align-items-center mb-4 wow fadeIn" data-wow-delay="0.6s">
                        <div class="bg-primary d-flex align-items-center justify-content-center rounded" style="width: 60px; height: 60px;">
                            <i class="fa fa-phone-alt text-white"></i>
                        </div>
                        <div class="ps-4">
                            <h5 class="mb-2">Call to ask any question</h5>
                            <h4 class="text-primary mb-0">+012 345 6789</h4>
                        </div>
                    </div>
                    <a href="quote.html" class="btn btn-primary py-3 px-5 mt-3 wow zoomIn" data-wow-delay="0.9s">Request A Quote</a>
                </div>
                <div class="col-lg-5" style="min-height: 500px;">
                    <div class="position-relative h-100">
                        <img class="position-absolute w-100 h-100 rounded wow zoomIn" data-wow-delay="0.9s" src="{% static 'img/about.jpg' %}" style="object-fit: cover;">
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- About End -->
{% endblock content %}

employees/templates/employees/blog.htm
{% extends "employees/base.htm" %}
{% load static %}
{% block content %}
  

<!-- Blog Start -->
    <div class="container-fluid py-5 wow fadeInUp" data-wow-delay="0.1s">
        <div class="container py-5">
            <div class="section-title text-center position-relative pb-3 mb-5 mx-auto" style="max-width: 600px;">
                <h5 class="fw-bold text-primary text-uppercase">Latest Blog</h5>
                <h1 class="mb-0">Read The Latest Articles from Our Blog Post</h1>
            </div>
            <div class="row g-5">
                
            {% if posts %}
                
                {% for post in posts%}
                  
                
                <div class="col-lg-4 wow slideInUp" data-wow-delay="0.3s">
                    <div class="blog-item bg-light rounded overflow-hidden">
                        <div class="blog-img position-relative overflow-hidden">
                            {% if post.image %}
                            <img class="img-fluid" src="{{post.image.url}}" alt="" style="width:350px; height:300px">
                            {% else %}
                            <p>No image</p>
                            {% endif %}
                            <a class="position-absolute top-0 start-0 bg-primary text-white rounded-end mt-5 py-2 px-4" href="">{{ post.posttype }}</a>
                        </div>
                        <div class="p-4">
                            <div class="d-flex mb-3">
                                <small class="me-3"><i class="far fa-user text-primary me-2"></i>{{ post.author }}</small>
                                <small><i class="far fa-calendar-alt text-primary me-2"></i>{{ post.updated_at }}</small>
                            </div>
                            <h4 class="mb-3">{{ post.title }}</h4>
                            <p>{{ post.description }}</p>
                            <a class="text-uppercase" href="{% url 'employees:post-detail' post.id %}">Read More <i class="bi bi-arrow-right"></i></a>
                        </div>
                    </div>
                
            </div>
            {% endfor %}

            {% else %}
                <p>No posts yet</p>
        {% endif %}
        
        </div>
    </div>
    <!-- Blog Start -->
{% endblock content %}

employees/templates/employees/contact.htm
{% extends "employees/base.htm" %}
{% load static %}

{% block content %}
<!-- Contact Start -->
<div class="container-fluid py-5 wow fadeInUp" data-wow-delay="0.1s">
    <div class="container py-5">
        <div class="section-title text-center position-relative pb-3 mb-5 mx-auto" style="max-width: 600px;">
            <h5 class="fw-bold text-primary text-uppercase">Contact Us</h5>
            <h1 class="mb-0">If You Have Any Query, Feel Free To Contact Us</h1>
        </div>
        <div class="row g-5 mb-5">
            <div class="col-lg-4">
                <div class="d-flex align-items-center wow fadeIn" data-wow-delay="0.1s">
                    <div class="bg-primary d-flex align-items-center justify-content-center rounded" style="width: 60px; height: 60px;">
                        <i class="fa fa-phone-alt text-white"></i>
                    </div>
                    <div class="ps-4">
                        <h5 class="mb-2">Call to ask any question</h5>
                        <h4 class="text-primary mb-0">+254755634231</h4>
                    </div>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="d-flex align-items-center wow fadeIn" data-wow-delay="0.4s">
                    <div class="bg-primary d-flex align-items-center justify-content-center rounded" style="width: 60px; height: 60px;">
                        <i class="fa fa-envelope-open text-white"></i>
                    </div>
                    <div class="ps-4">
                        <h5 class="mb-2">Email to get free quote</h5>
                       <a href="mailto:unclepedits.com@gmail.com"><h4 class="text-primary mb-0">unclepedits.com@gmail.com</h4></a>
                    </div>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="d-flex align-items-center wow fadeIn" data-wow-delay="0.8s">
                    <div class="bg-primary d-flex align-items-center justify-content-center rounded" style="width: 60px; height: 60px;">
                        <i class="fa fa-map-marker-alt text-white"></i>
                    </div>
                    <div class="ps-4">
                        <h5 class="mb-2">Visit our office</h5>
                        <h4 class="text-primary mb-0">Nakuru, Kenya</h4>
                    </div>
                </div>
            </div>
        </div>
        <div class="row g-5">
            <div class="col-lg-6 card pt-md-2 wow slideInUp" data-wow-delay="0.3s">
                <form method="post" action="">
                    {% csrf_token %}
                    <div class="row g-3">
                        <div class="col-md-6">
                            <input type="text" name="username" class="form-control border-0 bg-light px-4" placeholder="Your Name" style="height: 55px;">
                        </div>
                        <div class="col-md-6">
                            <input type="email" name="email" class="form-control border-0 bg-light px-4" placeholder="Your Email" style="height: 55px;">
                        </div>
                        <div class="col-12">
                            <input type="text" name="subject" class="form-control border-0 bg-light px-4" placeholder="Subject" style="height: 55px;">
                        </div>
                        <div class="col-12">
                            <textarea name="message" class="form-control border-0 bg-light px-4 py-3" rows="4" placeholder="Message"></textarea>
                        </div>
                        <div class="col-12">
                            <button class="btn btn-primary w-100 py-3" type="submit">Send Message</button>
                        </div>
                    </div>
                </form>
            </div>
            <div class="col-lg-6 wow slideInUp" data-wow-delay="0.6s">
                <iframe class="position-relative rounded w-100 h-100"
                src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d798.2110724638531!2d36.07899762924152!3d-0.3037014693364305!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x182f155a974682d5%3A0x11a56f87bbd3f8e9!2sEgerton%20University%2C%20Nakuru!5e0!3m2!1sen!2ske!4v1631616968615!5m2!1sen!2ske"
                frameborder="0" style="min-height: 350px; border:0;" allowfullscreen="" aria-hidden="false" tabindex="0">
                </iframe>



            </div>
        </div>
    </div>
</div>
<!-- Contact End -->
{% endblock content %}

employees/templates/employees/delete-post.htm
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/style2.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css?family=Alex+Brush&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Qwigley">
    <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700;800&family=Rubik:wght@400;500;600;700&display=swap" rel="stylesheet">

    <!-- Icon Font Stylesheet -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="{% static 'css/owl.carousel.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/animate.min.css' %}" rel="stylesheet">

    <!-- Customized Bootstrap Stylesheet -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
</head>
<body>
    <div class="container-fluid bg-dark px-5 d-none d-lg-block">
        <div class="row gx-0">
            <div class="col-lg-8 text-center text-lg-start mb-2 mb-lg-0">
                <div class="d-inline-flex align-items-center" style="height: 45px;">
                    <small class="me-3 text-light"><i class="fa fa-map-marker-alt me-2"></i>Nakuru, Kenya</small>
                    <small class="me-3 text-light"><i class="fa fa-phone-alt me-2"></i>0734452657</small>
                    <small class="text-light"><i class="fa fa-envelope-open me-2"></i>unclepedits.com@gmail.com</small>
                </div>
            </div>
            <div class="col-lg-4 text-center text-lg-end">
                <div class="d-inline-flex align-items-center" style="height: 45px;">
                    <a class="btn btn-sm btn-outline-light btn-sm-square rounded-circle me-2" href=""><i class="fab fa-twitter fw-normal"></i></a>
                    <a class="btn btn-sm btn-outline-light btn-sm-square rounded-circle me-2" href=""><i class="fab fa-facebook-f fw-normal"></i></a>
                    <a class="btn btn-sm btn-outline-light btn-sm-square rounded-circle me-2" href=""><i class="fab fa-linkedin-in fw-normal"></i></a>
                    <a class="btn btn-sm btn-outline-light btn-sm-square rounded-circle me-2" href=""><i class="fab fa-instagram fw-normal"></i></a>
                    <a class="btn btn-sm btn-outline-light btn-sm-square rounded-circle" href=""><i class="fab fa-youtube fw-normal"></i></a>
                </div>
            </div>
        </div>
    </div>
    <!-- Topbar End -->


    <!-- Navbar & Carousel Start -->
    <div class="container-fluid position-relative p-0 mt-md-2">
        <nav class="navbar navbar-expand-lg sticky-top px-5 py-3 py-lg-0">
            <a href="{% url 'employees:home-page' %}" class="navbar-brand p-0">
                <h3 class="m-0 text-primary qwi" style="font-size:40px;"><i class="fa fa-laptop me-2"></i>Uncle P Edits</h3>
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
                <span class="fa fa-bars"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <div class="navbar-nav ms-auto py-0">
                    <a href="{% url 'employees:home-page' %}" class="nav-item nav-link active">Home</a>
                    <a href="{% url 'employees:about-page' %}" class="nav-item nav-link">About</a>
                    <a href="{% url 'employees:service-page' %}" class="nav-item nav-link">Services</a>
                    <div class="nav-item dropdown">
                        
                    <a href="{% url 'employees:contact-page' %}" class="nav-item nav-link">Contact</a>
                </div>
                <butaton type="button" class="btn text-primary ms-3" data-bs-toggle="modal" data-bs-target="#searchModal"><i class="fa fa-search"></i></butaton>
                {% if user.is_authenticated %}
                <a href="{% url 'employees:home-page' %}" class="btn btn-warning py-2 px-4 ms-3">Logged in as {{request.user.username}}</a>
                <a href="{% url 'employees:logout-page' %}" class="btn btn-primary py-2 px-4 ms-3">Logout</a>
                {% else %}
                <a href="{% url 'employees:register-page' %}" class="btn btn-primary py-2 px-4 ms-3">Sign Up</a>
                <a href="{% url 'employees:login-page' %}" class="btn btn-warning py-2 px-4 ms-3">Login</a>
                {% endif %}
            </div>
        </nav>

        {% if messages %}

        {% for message in messages %}

        <div class="alert alert-dismissible fade-message {% if message.tags %} alert-{{ message.tags }} {% endif %}" role="alert">
           <div class="message-container">

            <div class="message-content"> 
                    {{ message }} 
                </div>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span class="" aria-hidden="true"><i class="fas fa-times"></i></span>
                </button>
            </div>
        </div>     
        
          
        {% endfor %}
        
      {% endif %}
      
      <h3 class="mb-md-2">Are you sure you want to delete the post?</h3>
      <form action="" method="post">
        {% csrf_token %}
        <input type="submit" value="Yes" class="btn btn-danger">
        <button class="mt-md-2 btn btn-warning" onclick="location.href='blog/'">Cancel</button>
      </form>
      <a href="{% url 'employees:blog-page' %}" class="btn btn-primary mt-md-3">Back to Blog</a>
      <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
      
      <script>
          $(document).ready(function () {
              // Add a click event handler to the close button
              $(".alert .close").on("click", function () {
                  $(this).parent(".alert").addClass("fade-out");
                  // Remove the alert element after the fade-out animation
                  setTimeout(function () {
                      $(this).parent(".alert").remove();
                  }, 500); // Adjust the duration to match your CSS transition
              });
          });
      </script>
</body>
</html>

employees/templates/employees/post-details.htm
<!-- post_detail.html -->

{% extends "employees/base.htm" %}
{% load static %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <h1>{{ post.title }}</h1>
            <p class="text-muted">Published by <strong class="text-bg-warning p-1" style="color:blueviolet;">{{ post.author }} </strong>on <strong>{{ post.updated_at }}</strong></p>
        </div>
    </div>
    <hr>
    <div class="row">
        <div class="col-md-3">
            <!-- Margin on the left for the image -->
            {% if post.image %}
            <img src="{{ post.image.url }}" alt="{{ post.title }}" class="img-fluid ml-3">
            {% else %}
            <p>No image</p>
            {%endif %}
        </div>
        <div class="col-md-6">
            <!-- Content or description on the right of the image -->
            <p>{{ post.description }}</p>
            {% if user.is_authenticated %}
            <div class="btn-group">
                <a href="{% url 'employees:post-page' %}" class="btn btn-sm btn-primary">
                    <i class="fas fa-plus"></i>
                </a>
                <a href="{% url 'employees:home-page' %}" class="btn btn-sm btn-info">
                    <i class="fas fa-eye"></i>
                </a>
                <a href="{% url 'employees:post-update' post.id %}" class="btn btn-sm btn-warning">
                    <i class="fas fa-pencil-alt"></i>
                </a>
                <a href="{% url 'employees:post-delete' post.id %}" class="btn btn-sm btn-danger">
                    <i class="fas fa-trash"></i>
                </a>
            </div>
            {% endif %}
            
            <!-- You can display other post details here as needed -->
            <a href="{% url 'employees:blog-page' %}" class="btn btn-primary">Back to Blog</a>
        </div>
    </div>
</div>
{% endblock %}